//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidas_Cartas
    {
        public string idPartidasCartas { get; set; }
        public Nullable<int> idCarta { get; set; }
        public string IdPartida { get; set; }
    
        public virtual Cartas Cartas { get; set; }
        public virtual Partidas Partidas { get; set; }
    }
}
